# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_name',
            new_name='name',
        ),
    ]
