# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=25)),
                ('language', models.CharField(max_length=45)),
                ('themes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Themes')),
            ],
        ),
    ]
