# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171126_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_date',
            field=models.CharField(max_length=20),
        ),
    ]
