# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_advertiser_category_city_themephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypedWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('previous_word_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TypedWords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.User')),
            ],
        ),
    ]
