# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_typedwords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='typedwords',
            old_name='previous_word_id',
            new_name='previous_word',
        ),
    ]
