# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171127_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=255)),
                ('pub_date', models.DateField()),
                ('acceptance_id', models.IntegerField(null=True)),
                ('rejection_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='TargetedAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertisement')),
            ],
        ),
        migrations.AddField(
            model_name='target',
            name='targeted_age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.TargetedAge'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Target'),
        ),
    ]
