# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171127_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_date', models.DateField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertiser')),
            ],
        ),
        migrations.CreateModel(
            name='RejectedAdvertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Advertiser')),
            ],
        ),
    ]
