# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_acceptedadvertisement_rejectedadvertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typedwords',
            name='previous_word',
        ),
        migrations.RemoveField(
            model_name='typedwords',
            name='word',
        ),
        migrations.AddField(
            model_name='typedwords',
            name='sentence',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
